version: '3.8'

services:
  pg-2:
    extends:
      file: common.yml
      service: postgres-common
    container_name: pg-2
    hostname: pg-2
    environment:
      REPMGR_NODE_NAME: pg-node-2
      REPMGR_NODE_NETWORK_NAME: pg-node-2

  pgpool-2:
    extends:
      file: common.yml
      service: pgpool-common
    container_name: pgpool-2
    hostname: pgpool-2
    depends_on:
      - pg-2
