version: '3.8'

x-postgres-common: &postgres-common
  image: docker.io/bitnami/postgresql-repmgr:11
  #  restart: always
  networks:
    - postgresql-network
  healthcheck:
    test: 'pg_isready -U postgres --dbname=postgres'
    interval: 10s
    timeout: 5s
    retries: 5

x-postgres-environment: &postgres-environment
  POSTGRESQL_POSTGRES_PASSWORD: postgres
  POSTGRESQL_USERNAME: postgres
  POSTGRESQL_PASSWORD: postgres
  POSTGRESQL_DATABASE: postgres
  POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS: 1
  REPMGR_USERNAME: repmgr
  REPMGR_PASSWORD: repmgrpassword



x-pgpool-common: &pgpool-common
  image: docker.io/bitnami/pgpool:4
  #  restart: always
  networks:
    - postgresql-network

  healthcheck:
    test: [ "CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh" ]
    interval: 10s
    timeout: 5s
    retries: 5

x-pgpool-environment: &pgpool-environment
  PGPOOL_SR_CHECK_USER: postgres
  PGPOOL_SR_CHECK_PASSWORD: postgres
  PGPOOL_ENABLE_LDAP: no
  PGPOOL_POSTGRES_USERNAME: postgres
  PGPOOL_POSTGRES_PASSWORD: postgres
  PGPOOL_ADMIN_USERNAME: postgres
  PGPOOL_ADMIN_PASSWORD: postgres
  PGPOOL_POSTGRES_CUSTOM_USERS: customuser
  PGPOOL_POSTGRES_CUSTOM_PASSWORDS: custompassword
  PGPOOL_ENABLE_LOAD_BALANCING: yes
  PGPOOL_AUTO_FAILBACK: yes
  PGPOOL_ENABLE_WATCHDOG: yes
  PGPOOL_MAX_POOL: 15
  PGPOOL_CONNECTION_LIFE_TIME: 0
  PGPOOL_HEALTH_CHECK_MAX_RETRIES: 5
  PGPOOL_NUM_INIT_CHILDREN: 32

x-pgpool-export: &pgpool-export
  expose:
    - 9000 # watchdog accepts connections
    - 9694 # UDP port for receiving Watchdog's heartbeat signal
    - 9898 # PCP process accepts connections
    - 9999 # Pgpool-II accepts connections
x-pgpool-port: &pgpool-port
  ports:
    - 9000:9000
    - 9694:9694
    - 9898:9898
    - 9999:9999

services:
  pg-1:
    <<: *postgres-common
    ports:
      - 15432:5432
    expose:
      - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      <<: *postgres-environment
      REPMGR_PRIMARY_HOST: pg-1
      REPMGR_PARTNER_NODES: pg-1,pg-2,pg-3
      REPMGR_NODE_NAME: pg-1
      REPMGR_NODE_NETWORK_NAME: pg-1

  pg-2:
    <<: *postgres-common
    ports:
      - 15433:5432
    expose:
      - 5432
    volumes:
      - pg_2_data:/bitnami/postgresql
    environment:
      <<: *postgres-environment
      REPMGR_PRIMARY_HOST: pg-1
      REPMGR_PARTNER_NODES: pg-1,pg-2,pg-3
      REPMGR_NODE_NAME: pg-2
      REPMGR_NODE_NETWORK_NAME: pg-2
    depends_on:
      - pg-1

  pg-3:
    <<: *postgres-common
    ports:
      - 15434:5432
    expose:
      - 5432
    volumes:
      - pg_3_data:/bitnami/postgresql
    environment:
      <<: *postgres-environment
      REPMGR_PRIMARY_HOST: pg-1
      REPMGR_PARTNER_NODES: pg-1,pg-2,pg-3
      REPMGR_NODE_NAME: pg-3
      REPMGR_NODE_NETWORK_NAME: pg-3
    depends_on:
      - pg-2

  pgpool-1:
    <<: *pgpool-common
    ports:
      - 25432:5432
    environment:
      <<: *pgpool-environment
      PGPOOL_BACKEND_NODES: 0:pg-1:5432,1:pg-2:5432,2:pg-3:5432
      PGPOOL_WD_HOSTNAME: pgpool-1
      PGPOOL_WD_PORT: 9000
    depends_on:
      - pg-1
      - pg-2
      - pg-3

  pgpool-2:
    <<: *pgpool-common
    ports:
      - 25433:5432
    environment:
      <<: *pgpool-environment
      PGPOOL_BACKEND_NODES: 0:pg-1:5432,1:pg-2:5432,2:pg-3:5432
      PGPOOL_WD_HOSTNAME: pgpool-2
      PGPOOL_WD_PORT: 9000
    depends_on:
      - pg-1
      - pg-2
      - pg-3

  pgpool-3:
    <<: *pgpool-common
    ports:
      - 25434:5432
    environment:
      <<: *pgpool-environment
      PGPOOL_BACKEND_NODES: 0:pg-1:5432,1:pg-2:5432,2:pg-3:5432
      PGPOOL_WD_HOSTNAME: pgpool-3
      PGPOOL_WD_PORT: 9000
    depends_on:
      - pg-1
      - pg-2
      - pg-3

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    networks:
      - postgresql-network
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./data/pgadmin/:/var/lib/pgadmin
    depends_on:
      - pg-1
      - pg-2
      - pg-3

networks:
  postgresql-network:
    driver: bridge

volumes:
  pg_1_data:
    driver: local
  pg_2_data:
    driver: local
  pg_3_data:
    driver: local