version: '3.8'

services:
  pg-1:
    extends:
      file: common.yml
      service: postgres-common
    container_name: pg-1
    hostname: pg-1
    environment:
      REPMGR_NODE_NAME: pg-node-1
      REPMGR_NODE_NETWORK_NAME: pg-node-1

  pgpool-1:
    extends:
      file: common.yml
      service: pgpool-common
    container_name: pgpool-1
    hostname: pgpool-1
    depends_on:
      - pg-1
