version: '3.8'

services:
  pg-3:
    extends:
      file: common.yml
      service: postgres-common
    container_name: pg-3
    hostname: pg-3
    environment:
      REPMGR_NODE_NAME: pg-node-3
      REPMGR_NODE_NETWORK_NAME: pg-node-3

  pgpool-3:
    extends:
      file: common.yml
      service: pgpool-common
    container_name: pgpool-3
    hostname: pgpool-3
    environment:
      PGPOOL_WD_HOSTNAME: pg-node-3
      PGPOOL_WD_PORT: 9000
    depends_on:
      - pg-3
