version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    network_mode: "host"
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./data/pgadmin/:/var/lib/pgadmin