version: '3.8'

services:
  pg-1:
    extends:
      file: common.yml
      service: postgres-common
    container_name: pg-1
    hostname: pg-1
    volumes:
      - ./data:/bitnami/postgresql
    environment:
      REPMGR_NODE_NAME: pg-node-1
      REPMGR_NODE_NETWORK_NAME: pg-node-1

  pgpool-1:
    extends:
      file: common.yml
      service: pgpool-common
    container_name: pgpool-1
    hostname: pgpool-1
    environment:
      PGPOOL_WD_HOSTNAME: pg-node-1
      PGPOOL_WD_PORT: 9000
    depends_on:
      - pg-1

#volumes:
#  pg_1_data:
#    driver: local