version: '3.8'

x-postgres-common: &postgres-common
  image: docker.io/bitnami/postgresql-repmgr:11
  #  restart: always
  network_mode: "host"
  healthcheck:
    test: 'pg_isready -U postgres --dbname=postgres'
    interval: 10s
    timeout: 5s
    retries: 5

x-postgres-environment: &postgres-environment
  POSTGRESQL_POSTGRES_PASSWORD: postgres
  POSTGRESQL_USERNAME: postgres
  POSTGRESQL_PASSWORD: postgres
  POSTGRESQL_DATABASE: postgres
  POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS: 1
  REPMGR_USERNAME: repmgr
  REPMGR_PASSWORD: repmgrpassword

x-postgres-expose: &postgres-expose
  expose:
    - 5432
x-postgres-port: &postgres-port
  ports: # 1 개 장비에서 테스트 하므로 각 포트를 다르게 설정
    - 25432:5432


x-pgpool-common: &pgpool-common
  image: docker.io/bitnami/pgpool:4
  #  restart: always
  network_mode: "host"
  healthcheck:
    test: [ "CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh" ]
    interval: 10s
    timeout: 5s
    retries: 5

x-pgpool-environment: &pgpool-environment
  PGPOOL_SR_CHECK_USER: postgres
  PGPOOL_SR_CHECK_PASSWORD: postgres
  PGPOOL_ENABLE_LDAP: no
  PGPOOL_POSTGRES_USERNAME: postgres
  PGPOOL_POSTGRES_PASSWORD: postgres
  PGPOOL_ADMIN_USERNAME: postgres
  PGPOOL_ADMIN_PASSWORD: postgres
  PGPOOL_POSTGRES_CUSTOM_USERS: customuser
  PGPOOL_POSTGRES_CUSTOM_PASSWORDS: custompassword
  PGPOOL_ENABLE_LOAD_BALANCING: yes
  PGPOOL_AUTO_FAILBACK: yes
  PGPOOL_ENABLE_WATCHDOG: yes
  PGPOOL_MAX_POOL: 15
  PGPOOL_CONNECTION_LIFE_TIME: 0
  PGPOOL_HEALTH_CHECK_MAX_RETRIES: 5
  PGPOOL_NUM_INIT_CHILDREN: 32

x-pgpool-expose: &pgpool-expose
  expose:
    - 9000 # watchdog accepts connections
    - 9694 # UDP port for receiving Watchdog's heartbeat signal
    - 9898 # PCP process accepts connections
    - 9999 # Pgpool-II accepts connections
x-pgpool-port: &pgpool-port
  ports: # 1 개 장비에서 테스트 하므로 각 포트를 다르게 설정
    - 29000:9000
    - 29694:9694
    - 29898:9898
    - 29999:9999

services:
  pg-2:
    <<: *postgres-common
    <<: *postgres-port
    <<: *postgres-expose
    volumes:
      - pg_2_data:/bitnami/postgresql
    environment:
      <<: *postgres-environment
      REPMGR_PRIMARY_HOST: pg-2
      REPMGR_PARTNER_NODES: pg-1,pg-2,pg-3
      REPMGR_NODE_NAME: pg-2
      REPMGR_NODE_NETWORK_NAME: pg-2

  pgpool-1:
    <<: *pgpool-common
    <<: *pgpool-port
    <<: *pgpool-expose
    environment:
      <<: *pgpool-environment
      PGPOOL_BACKEND_NODES: 0:pg-1:15432,1:pg-2:25432,2:pg-3:35432
      PGPOOL_WD_HOSTNAME: pgpool-2
      PGPOOL_WD_PORT: 9000
    depends_on:
      - pg-2

volumes:
  pg_2_data:
    driver: local